// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brcgtyygezcnvnxxgsad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyY2d0eXlnZXpjbnZueHhnc2FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MTAyNTAsImV4cCI6MjA2ODE4NjI1MH0.A1SWAw-QbEX42kOsdJViAsyPf8QPqT4ig59uDLE2Ib0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});